# values.yaml

image:
  repository: volzfr/berger-status-service
  tag: 2901
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

fullnameOverride: faaast-status-berger

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - fa3st Service
    nginx.ingress.kubernetes.io/auth-secret: faaast-service-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  tls:
    - hosts:
        - fa3st.aberger.factory-x.catena-x.net
      secretName: tls-secret-fa3st.aberger
  hosts:
    - host: fa3st.aberger.factory-x.catena-x.net
      paths:
        - path: /
          pathType: Prefix
          

autoscaling:
  enabled: false
serviceAccount:
  # Specifies whether a service account should be created
  create: false
