{{- if .Values.fa3st.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fa3st.basicAuth.secretName }}
type: Opaque
data:
  auth: {{ .Values.fa3st.basicAuth.htpasswd | b64enc }}
{{- end }}