apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faaast-service.fullname" . }}-config
  labels:
    {{- include "faaast-service.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "persistence": {
        "@class": "{{ .Values.fa3st.persistence.class }}"
      },
      "messageBus": {
        "@class": "{{ .Values.fa3st.messageBus.class }}",
        "host": "{{ .Values.fa3st.messageBus.host }}",
        "user": "{{ .Values.fa3st.messageBus.user }}",
        "password": "{{ .Values.fa3st.messageBus.password }}"
      },
      "endpoints": [
        {
          "@class": "{{ (index .Values.fa3st.endpoints 0).class }}",
          "port": {{ (index .Values.fa3st.endpoints 0).port }},
          "corsEnabled": {{ (index .Values.fa3st.endpoints 0).corsEnabled }},
          "sslEnabled": {{ (index .Values.fa3st.endpoints 0).sslEnabled }}
        }
      ]
    }