apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "faaast-service.fullname" . }}
  labels:
    {{- include "faaast-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.fa3st.autoscaling.enabled }}
  replicas: {{ .Values.fa3st.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "faaast-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.fa3st.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "faaast-service.labels" . | nindent 8 }}
        {{- with .Values.fa3st.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.fa3st.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "faaast-service.serviceAccountName" . }}
      {{- with .Values.fa3st.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: faaast-service
          {{- with .Values.fa3st.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.fa3st.image.repository }}:{{ .Values.fa3st.image.tag | default .Chart.AppVersion }}"
          args:
            - "-c"
            - "/app/config/config.json"
          imagePullPolicy: {{ .Values.fa3st.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ (index .Values.fa3st.endpoints 0).port }}
              protocol: TCP
          {{- with .Values.fa3st.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.fa3st.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.fa3st.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.fa3st.config.mountPath }}
              subPath: config.json
            {{- with .Values.fa3st.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "faaast-service.fullname" . }}-config
        {{- with .Values.fa3st.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.fa3st.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fa3st.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fa3st.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
