apiVersion: v1
kind: Service
metadata:
  name: {{ include "faaast-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "faaast-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.fa3st.service.type }}
  ports:
    - port: {{ .Values.fa3st.service.port }}
      targetPort: 8081
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "faaast-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}