apiVersion: v1
kind: Service
metadata:
  name: {{ include "berger-service.fullname" . }}
  labels:
    {{- include "berger-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ (index .Values.endpoints 0).port }}
      protocol: TCP
      name: https
  selector:
    {{- include "berger-service.selectorLabels" . | nindent 4 }}
