apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "faaast-service.fullname" . }}
  labels:
    {{- include "faaast-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.berger-service.autoscaling.enabled }}
  replicas: {{ .Values.berger-service.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "faaast-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "faaast-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.berger-service.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "faaast-service.labels" . | nindent 8 }}
        {{- with .Values.berger-service.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "faaast-service.serviceAccountName" . }}
      {{- with .Values.berger-service.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.berger-service.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.berger-service.image.repository }}:{{ .Values.berger-service.image.tag | default .Chart.AppVersion }}"
          args:
            - "-c"
            - "/app/config/config.json"
          imagePullPolicy: {{ .Values.berger-service.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.berger-service.service.port }}
              protocol: TCP
          {{- with .Values.berger-service.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.berger-service.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.berger-service.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.berger-service.config.mountPath }}
              subPath: config.json
            {{- with .Values.berger-service.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "faaast-service.fullname" . }}-config
        {{- with .Values.berger-service.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.berger-service.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.berger-service.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.berger-service.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
