# Default values for berger-service sub-chart
# These can be overridden from the parent chart's values.yaml under "berger-service:"

replicaCount: 1

image:
  repository: volzfr/berger-status-service
  tag: 2901
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

fullnameOverride: ""

config:
  mountPath: "/app/config/config.json"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - fa3st Service
    nginx.ingress.kubernetes.io/auth-secret: faaast-service-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  tls:
    - hosts:
        - fa3st.aberger.factory-x.catena-x.net
      secretName: tls-secret-fa3st.aberger
  hosts:
    - host: fa3st.aberger.factory-x.catena-x.net
      paths:
        - path: /status
          pathType: Prefix

autoscaling:
  enabled: false

serviceAccount:
  create: false

persistence:
  class: "de.fraunhofer.iosb.ilt.faaast.service.persistence.memory.PersistenceInMemory"

messageBus:
  class: "de.fraunhofer.iosb.ilt.faaast.service.messagebus.cloudevents.MessageBusCloudevents"
  host: "wss://mqttbroker.factory-x.catena-x.net:443"
  user: "fx-factory"
  password: "placeholder"

endpoints:
  - class: "de.fraunhofer.iosb.ilt.faaast.service.endpoint.http.HttpEndpoint"
    port: 8080
    corsEnabled: true
    sslEnabled: false
